# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  user_project_override = true
  billing_project       = var.project_id
  project               = var.project_id
}

provider "google-beta" {
  user_project_override = true
  billing_project       = var.project_id
  project               = var.project_id
}
